<?php
/* ###VERSIONSBLOCKINLCUDE### */

function generateUserLessFile($arVariables, $arSections) {
	if (!is_array($arVariables)) {
		$arVariables = array();
	}
	if (!is_array($arSections)) {
		$arSections = array();
	}
	$designLess = "// THIS FILE IS AUTOMATICALLY GENERATED! DO NOT CHANGE THIS FILE!!!\n".
				"// DIESE DATEI WIR AUTOMATISCH ERZEUGT! BITTE NICHT MANUELL ÄNDERN!!!\n\n".
				"// SECTIONS ENABLED: ".implode(",", array_keys($arSections))."\n\n";
	foreach ($arVariables as $variableName => $variableValue) {
		$designLess .= "@".$variableName.": ".$variableValue.";\n";
	}
	return $designLess;
}

if (!empty($_REQUEST["activate"])) {
	// Initialisierung
	require_once $ab_path. 'sys/lib.cache.adapter.php';
	$cacheAdapter = new CacheAdapter();
	// Änderung speichern
	$design = $_REQUEST["activate"];
	$db->querynow("UPDATE `option` SET value='".mysql_escape_string($design)."'
			WHERE plugin='SITE' AND typ='TEMPLATE'");
	$nar_systemsettings["SITE"]["TEMPLATE"] = $design;
	// Optionen neu cachen
	$data = $db->fetch_table("select * from `option` order by plugin, typ");
	$ar = array ();
	foreach ($data as $row)
		$ar[$row['plugin']][$row['typ']] = $row['value'];
	$s_code = '<?'. 'php $nar_systemsettings = '. php_dump($ar, 0). '; ?'. '>';
	$fp = fopen('../cache/option.php', 'w');
	fputs($fp, $s_code);
	fclose($fp);
	// Templates neu cachen
	$cacheAdapter->cacheAll();
	// Weiterleiten
	die(forward("index.php?page=design"));
}

include $ab_path."sys/lib.template.design.php";

$designs = TemplateDesignManagement::getInstance($db);
$ar_list = array();
$directory = dir($ab_path."design");

while (false !== ($entry = $directory->read())) {
	if (($entry == ".") || ($entry == "..") || ($entry == "default") || !is_dir($ab_path."design/".$entry))
		continue;
	if ($designs->existDesign($entry)) {
		$ar_current = $designs->getDesignInformation($entry);
		$ar_current["languages"] = array();
		// Sprachen auslesen
		$directory_design = dir($ab_path."design/".$entry);
		while (false !== ($lang_current = $directory_design->read())) {
			if (($lang_current == ".") || ($lang_current == "..") || !is_dir($ab_path."design/".$entry."/".$lang_current))
				continue;
			$ar_current["languages"][] = $lang_current;
		}
		$ar_current["languages"] = " - ".implode("\n - ", $ar_current["languages"]);
		// Aktiv?
		if ($entry == $nar_systemsettings["SITE"]["TEMPLATE"]) {
			$ar_current["active"] = 1;
		}
		// Eintrag hinzufügen
		$ar_list[] = $ar_current;
	}
}
$tpl_content->addlist("liste", $ar_list, "tpl/de/design.row.htm");

$cacheFileLessVars = $ab_path."cache/design/resources/".$s_lang."/css/design.vars.php";
$designTpl = $nar_systemsettings["SITE"]["TEMPLATE"];
$designLessConfigDir = $ab_path."design/".$designTpl."/default/resources/css";
$designLessConfigFile = $designLessConfigDir."/config_user.less";
/*
$arLessGroups = array(
	"design_base"		=>	array("design-background", "design-text-color", "design-link-color", "design-link-hover-color"),
	"design_highlight"	=>	array("design-highlight-background", "design-highlight-text-color", "design-highlight-link-color", "design-highlight-link-hover-color"),
	"design_contrast"	=>	array("design-contrast-background", "design-contrast-text-color", "design-contrast-link-color", "design-contrast-link-hover-color"),
	"design_menline"	=>	array("design-menline-background", "design-menline-border", "design-menline-text-color", "design-menline-link-color", "design-menline-link-hover-color"),
	"design_header"		=>	array("design-header-background", "design-header-border", "design-header-text-color", "design-header-link-color", "design-header-link-hover-color"),
	"design_colors"		=>	array("design-color-primary", "design-color-primary-text", "design-color-secondary", "design-color-secondary-text", 
							"design-color-success", "design-color-success-text", "design-color-warning", "design-color-warning-text", "design-color-danger", "design-color-danger-text")
);
*/
$arLessEnabled = array();
$arLessVariables = array();
$arLessVariablesCustom = array();

// Less-Variablen auslesen
if (file_exists($cacheFileLessVars)) {
	include $cacheFileLessVars;
	if (is_array($arLessVariables) && array_key_exists("NVP", $arLessVariables)) {
		$arLessVariables = $arLessVariables["NVP"];
	}
}
// Design konfiguration auslesen
if (file_exists($designLessConfigFile)) {
	$designLessConfigContent = file_get_contents($designLessConfigFile);
	if (preg_match("/\/\/ SECTIONS ENABLED: (.+)/", $designLessConfigContent, $arSectionsMatch)) {
		$arSectionsEnabled = explode(",", $arSectionsMatch[1]);
		foreach ($arSectionsEnabled as $sectionIndex => $sectionName) {
			$arLessEnabled[$sectionName] = 1;
		}
	}
}

$hashAccess = sha1(file_get_contents($ab_path."inc.server.php"));
// Design einstellungen
if ($_POST["do"] == "designPreview") {
	if (array_key_exists("enabled", $_POST)) {
		$arLessEnabled = $_POST["enabled"];
	}
	if (array_key_exists("variables", $_POST)) {
		$arLessVariablesCustom = $_POST["variables"];
		$arLessVariables = array_merge($arLessVariables, $arLessVariablesCustom);
	}
	system("cp ".$ab_path."cache/design/resources/".$s_lang."/css/*.less ".$ab_path."cache/design/resources/".$s_lang."/css-preview/");
	//$designLess = generateUserLessFile($_POST["variables"], $_POST["enabled"]);
	//file_put_contents($ab_path."cache/design/resources/".$s_lang."/css-preview/config_user.less", $designLess);
	$_POST["variables"]["@icon-font-path"] = '"../fonts/"';
	Design_Less_DesignCompiler::generateCss("resources/".$s_lang."/css/design.css", "cache/design/resources/".$s_lang."/css-preview/", $_POST["variables"]);
	header("Content-Type: application/json");
	die(json_encode(array("success" => true, "url" => $tpl_content->tpl_uri_action("system-admin,design,preview")."?nocache=".time()."&access=".$hashAccess )));
	//die(forward("index.php?page=design&do=designPreviewConfirm"));
}

if ($_POST["do"] == "designSave") {
	$designLess = generateUserLessFile($_POST["variables"], $_POST["enabled"]);
	// Create directory if not existing
	if (!is_dir($designLessConfigDir)) {
		mkdir($designLessConfigDir, 0777, true);
	}
	file_put_contents($designLessConfigFile, $designLess);
	Design_Less_DesignCompiler::generateCss("resources/".$s_lang."/css/design.css", NULL, array("@icon-font-path" => '"../fonts/"'));
	header("Content-Type: application/json");
	die(json_encode(array("success" => true, "url" => $tpl_content->tpl_uri_action("system-admin,design,preview_live")."?nocache=".time()."&access=".$hashAccess )));
	//die(forward("index.php?page=design&do=designSaveConfirm"));
}

$tpl_content->addvar("accessToken", $hashAccess);
$tpl_content->addvars($arLessEnabled, "enabled_");
$tpl_content->addvars($arLessVariables, "variables_");

?>