CREATE TABLE `article_stats` (
	`FK_USER` INT(10) UNSIGNED NOT NULL,
	`FK_AD` INT(10) UNSIGNED NOT NULL,
	`DATUM` DATE NOT NULL,
	`VIEWS` MEDIUMINT(8) UNSIGNED NOT NULL,
	PRIMARY KEY (`FK_USER`, `FK_AD`, `DATUM`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

ALTER TABLE `billing_invoice`
	ADD INDEX `STATUS` (`STATUS`);

ALTER TABLE `vendor`
ADD COLUMN `CREATED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `CHANGED`;