INSERT INTO `crontab` (`ID_CRONTAB`, `EINMALIG`, `FEHLER`, `SYSNAME`, `ERLEDIGT`, `PRIO`, `DSC`, `FIRST`, `LAST`, `EINHEIT`, `ALL_X`, `DATEI`, `FUNKTION`, `FK`, `CODE`) 
  VALUES (1248, NULL, 0, NULL, NULL, 1, 'Bestätigungscode für Lastschrift-Zahlung', '2017-03-24 18:00:00', '2017-03-26 12:34:03', 'day', 1, 'cron/payment_pincode_email.php', '', NULL, '');

INSERT INTO `option` (`plugin`, `typ`, `value`, `default_value`, `beschreibung`, `orderfeld`, `format`) 
  VALUES ('MARKTPLATZ', 'SEPADAY', '4', '4', 'Wie lange soll mit der Abbuchung gewartet werden', 0, '');

INSERT INTO `option` (`plugin`, `typ`, `value`, `default_value`, `beschreibung`, `orderfeld`, `format`) 
  VALUES ('MARKTPLATZ', 'PINCODE_EMAIL', '2', '4', 'Wie lange sollte warten, um E-Mail für Pincode zu senden', 0, '');

UPDATE `payment_adapter` SET `CONFIG`='EXPORTID=1234' WHERE  `ADAPTER_NAME`='DirectDebit';

ALTER TABLE `billing_invoice`
	ADD COLUMN `FK_BILLING_INVOICE_EXPORT` INT(11) UNSIGNED NOT NULL AFTER `FK_PAYMENT_ADAPTER`;

ALTER TABLE `user`
	ADD COLUMN `FK_USER_ACCOUNT_PINCODE_EXPORT` INT(11) NOT NULL DEFAULT '0' AFTER `FK_PAYMENT_ADAPTER`;
	
ALTER TABLE `user`
	ADD COLUMN `PAYMENT_ADAPTER_DIRECTDB_REQ_FLAG` TINYINT(4) NOT NULL DEFAULT '0' AFTER `PAYMENT_ADAPTER_SELLER_CONFIG`;
	
CREATE TABLE `billing_invoice_export` (
	`ID_BILLING_INVOICE_EXPORT` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`EXPORT_NO` BIGINT(20) UNSIGNED NOT NULL,
	`TOTAL_INVOICES` INT(10) UNSIGNED NOT NULL,
	`TOTAL_MONEY` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
	`FIRST_DATE` DATE NOT NULL,
	`LAST_DATE` DATE NOT NULL,
	`MARK_AS_PAID` TINYINT(4) NOT NULL DEFAULT '0',
	`STAMP` DATETIME NOT NULL,
	PRIMARY KEY (`ID_BILLING_INVOICE_EXPORT`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;

CREATE TABLE `user_account_pincode_export` (
	`ID_USER_ACCOUNT_PINCODE_EXPORT` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`EXPORT_NO` BIGINT(20) UNSIGNED NOT NULL,
	`TOTAL_USERS` INT(10) UNSIGNED NOT NULL,
	`TOTAL_MONEY` DECIMAL(10,2) UNSIGNED NOT NULL DEFAULT '0.00',
	`PINCODE_EMAIL` TINYINT(3) UNSIGNED NOT NULL DEFAULT '4',
	`IS_EMAIL_SENT` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`EMAIL_SENT_STAMP` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`STAMP` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`ID_USER_ACCOUNT_PINCODE_EXPORT`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM;
