INSERT INTO `option` (`plugin`, `typ`, `value`, `default_value`, `beschreibung`, `format`) 
	VALUES ('MARKTPLATZ', 'CHAT_SHOW_CONTACT', '0', '0', 'Kontaktdaten des Absenders bei Nachrichten darstellen', 'check');

ALTER TABLE `chat`
	ADD COLUMN `FK_CHAT_USER` INT(11) NULL DEFAULT NULL AFTER `SUBJECT`;
	
UPDATE `chat` SET 
	FK_CHAT_USER=(SELECT SENDER FROM `chat_message` WHERE FK_CHAT=ID_CHAT ORDER BY ID_CHAT_MESSAGE ASC LIMIT 1)
WHERE FK_CHAT_USER IS NULL;

ALTER TABLE `news`
	ADD COLUMN `SER_MEDIA` TEXT NULL AFTER `SER_IMAGES`;

ALTER TABLE `faqkat`
	ADD COLUMN `FK_NAV` BIGINT UNSIGNED NULL DEFAULT NULL AFTER `ID_FAQKAT`,
	ADD INDEX `FK_NAV` (`FK_NAV`);

CREATE TABLE `cache_storage` (
	`ID_CACHE_STORAGE` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`IDENT_HASH` VARCHAR(64) NOT NULL,
	`STAMP_VALID_UNTIL` DATETIME NOT NULL,
	`CONTENT` MEDIUMBLOB NOT NULL,
	PRIMARY KEY (`ID_CACHE_STORAGE`),
	UNIQUE INDEX `IDENT_HASH` (`IDENT_HASH`),
	INDEX `STAMP_VALID_UNTIL` (`STAMP_VALID_UNTIL`)
)
ENGINE=MyISAM;

CREATE TABLE `cache_storage_relation` (
	`FK_CACHE_STORAGE` INT(10) UNSIGNED NOT NULL,
	`RELATION_TYPE` VARCHAR(64) NOT NULL,
	`FK_RELATION` INT(10) UNSIGNED NOT NULL,
	UNIQUE INDEX `FK_CACHE_STORAGE_RELATION_TYPE_FK_RELATION` (`FK_CACHE_STORAGE`, `RELATION_TYPE`, `FK_RELATION`)
)
ENGINE=MyISAM;

INSERT INTO `crontab` (`PRIO`, `DSC`, `FIRST`, `EINHEIT`, `ALL_X`, `DATEI`, `FUNKTION`) 
	VALUES (1, 'Löschen von nicht mehr benötigten Daten (z.B. alte Cache-Dateien)', '2016-10-28 12:00:00', 'hour', 1, 'cron/cleanup.php', '');
