ALTER TABLE `user`
	CHANGE COLUMN `PAYMENT_ADAPTER_CONFIG` `PAYMENT_ADAPTER_CONFIG` MEDIUMTEXT NOT NULL DEFAULT '' AFTER `AUTOCONFIRM_VENDORS`,
	CHANGE COLUMN `PAYMENT_ADAPTER_SELLER_CONFIG` `PAYMENT_ADAPTER_SELLER_CONFIG` MEDIUMTEXT NOT NULL DEFAULT '' AFTER `PAYMENT_ADAPTER_CONFIG`;
	
UPDATE `infoseite` i 
JOIN `string_info` si ON si.S_TABLE='infoseite' AND si.FK=i.ID_INFOSEITE AND si.BF_LANG=128
SET i.B_SYS=1
WHERE si.V1 IN ('header meta', 'header scripts', 'CODE FUER WEBSTATISTIK');