ALTER TABLE `trade`
	ADD COLUMN `FK_AD_REQUEST` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `FK_AD_VARIANT`;
	
ALTER TABLE `trade`
	CHANGE COLUMN `BID_STATUS` `BID_STATUS` ENUM('ACTIVE','CANCEL','ENDED','ACCEPTED','REQUEST') NOT NULL DEFAULT 'ACTIVE' AFTER `STAMP_BID`;