CREATE TABLE `article_stats` (
	`FK_USER` INT(10) UNSIGNED NOT NULL,
	`FK_AD` INT(10) UNSIGNED NOT NULL,
	`DATUM` DATE NOT NULL,
	`VIEWS` MEDIUMINT(8) UNSIGNED NOT NULL,
	PRIMARY KEY (`FK_USER`, `FK_AD`, `DATUM`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

ALTER TABLE `billing_invoice`
	ADD INDEX `STATUS` (`STATUS`);

ALTER TABLE `vendor`
ADD COLUMN `CREATED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `CHANGED`;

CREATE TABLE `country_group` (
	`ID_COUNTRY_GROUP` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`BF_LANG_COUNTRY_GROUP` TINYINT(3) UNSIGNED NOT NULL,
	`FK_PARENT` INT(10) UNSIGNED NULL DEFAULT NULL,
	`SORT_INDEX` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`NS_LEFT` INT(10) UNSIGNED NOT NULL,
	`NS_RIGHT` INT(10) UNSIGNED NOT NULL,
	`NS_LEVEL` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`ID_COUNTRY_GROUP`),
	INDEX `TREE_PARENT_POS` (`FK_PARENT`, `SORT_INDEX`),
	INDEX `BF_LANG_COUNTRY_GROUP` (`BF_LANG_COUNTRY_GROUP`),
	INDEX `TREE_NESTED_SET` (`NS_LEFT`, `NS_RIGHT`, `NS_LEVEL`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

CREATE TABLE `string_country_group` (
	`S_TABLE` VARCHAR(16) NOT NULL DEFAULT '',
	`FK` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`BF_LANG` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`T1` LONGTEXT NULL,
	`V1` VARCHAR(255) NULL DEFAULT NULL,
	`V2` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`S_TABLE`, `FK`, `BF_LANG`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
ROW_FORMAT=DYNAMIC
;


CREATE TABLE `country_group_mapping` (
	`FK_COUNTRY` BIGINT(20) UNSIGNED NOT NULL,
	`FK_COUNTRY_GROUP` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`FK_COUNTRY`, `FK_COUNTRY_GROUP`)
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;

ALTER TABLE `ad_master`
	CHANGE COLUMN `BESCHREIBUNG` `BESCHREIBUNG` MEDIUMTEXT NOT NULL AFTER `PRODUKTNAME`,
	CHANGE COLUMN `VERSANDKOSTEN_INFO` `VERSANDKOSTEN_INFO` MEDIUMTEXT NULL AFTER `VERSANDOPTIONEN`,
	CHANGE COLUMN `AVAILABILITY` `AVAILABILITY` MEDIUMTEXT NULL AFTER `BF_CONSTRAINTS`,
	CHANGE COLUMN `IMPORT_IDENTIFIER` `IMPORT_IDENTIFIER` MEDIUMTEXT NULL AFTER `EAN`,
	CHANGE COLUMN `IMPORT_IMAGES` `IMPORT_IMAGES` MEDIUMTEXT NULL AFTER `IMPORT_IDENTIFIER`,
	CHANGE COLUMN `SER_FIELDS` `SER_FIELDS` MEDIUMTEXT NULL AFTER `IMPORT_SOURCE`;

ALTER TABLE `ad_master`
	ADD COLUMN `JSON_ADDITIONAL` MEDIUMTEXT NULL AFTER `SER_FIELDS`;

ALTER TABLE `lookup`
	CHANGE COLUMN `art` `art` VARCHAR(32) NOT NULL DEFAULT '' AFTER `f_system`;

ALTER TABLE `infoseite`
	ADD COLUMN `LU_INFO_BEREICHE` SMALLINT(5) UNSIGNED NULL DEFAULT NULL AFTER `USETYPE`,
	ADD INDEX `LU_INFO_BEREICHE` (`LU_INFO_BEREICHE`);
	
ALTER TABLE `ad_order`
	ADD COLUMN `SHIPPING_PROVIDER` VARCHAR(64) NULL DEFAULT NULL AFTER `FK_ARTICLE_EXT`,
	ADD INDEX `SHIPPING_PROVIDER` (`SHIPPING_PROVIDER`);
	
ALTER TABLE `user`
	ADD COLUMN `JSON_ADDITIONAL` MEDIUMTEXT NULL DEFAULT NULL AFTER `DEFAULT_CONSTRAINTS`;
	
INSERT INTO `option` (`plugin`, `typ`, `value`, `default_value`, `beschreibung`, `format`)
	VALUES ('MARKTPLATZ', 'HIDE_CONTACT_INFO', '1', '1', 'Kontaktdaten bei Verkäufen ausblenden solange der Verkauf nicht bestätigt wurde', 'check');

ALTER TABLE `newsview`
	ADD COLUMN `FK_USER` MEDIUMINT UNSIGNED NOT NULL AFTER `STAMP`;
ALTER TABLE `newsview`
	ADD INDEX `FK_USER` (`FK_USER`);

ALTER TABLE `chat`
	ADD INDEX `STAMP_CREATE` (`STAMP_CREATE`);

ALTER TABLE `calendar_event`
	ADD COLUMN `STAMP` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `DECLINE_REASON`;
ALTER TABLE `calendar_event`
	ADD INDEX `STAMP` (`STAMP`);

ALTER TABLE `job`
	ADD COLUMN `STAMP_CREATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `JOBNUMBER`;

ALTER TABLE `job`
	ADD INDEX `STAMP_CREATE` (`STAMP_CREATE`);

ALTER TABLE `ad_request`
	ADD COLUMN `STAMP_CREATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `LONGITUDE`;

ALTER TABLE `ad_request`
	ADD INDEX `STAMP_CREATE` (`STAMP_CREATE`);

ALTER TABLE `vendor_homepage`
	ADD COLUMN `STAMP_CREATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP AFTER `SER_DETAILS`;

ALTER TABLE `vendor_homepage`
	ADD INDEX `STAMP_CREATE` (`STAMP_CREATE`);

ALTER TABLE `billing_invoice`
	ADD COLUMN `STAMP_CORRECTION` DATE NULL DEFAULT NULL AFTER `STAMP_DUE`;

ALTER TABLE `usergroup`
	ADD COLUMN `FK_INFOSEITE` BIGINT UNSIGNED NULL AFTER `SER_OPTIONS`;

ALTER TABLE `trade`
	ADD INDEX `FK_NEGOTIATION_FK_USER_FROM_FK_USER_TO` (`FK_USER_FROM`, `FK_USER_TO`, `FK_NEGOTIATION`);

UPDATE `infoseite` i
JOIN `string_info` s ON s.S_TABLE='infoseite' AND s.FK=i.ID_INFOSEITE
SET
 i.LU_INFO_BEREICHE = (SELECT ID_LOOKUP FROM `lookup` WHERE art='INFO_BEREICHE' AND VALUE='RECHNUNG')
WHERE s.V1 LIKE "Rechnung%";

UPDATE `infoseite` i
JOIN `string_info` s ON s.S_TABLE='infoseite' AND s.FK=i.ID_INFOSEITE
SET
 i.LU_INFO_BEREICHE = (SELECT ID_LOOKUP FROM `lookup` WHERE art='INFO_BEREICHE' AND VALUE='USER-BACKEND')
WHERE s.V1 LIKE "User%";

INSERT INTO `perm` 
	VALUES (37, 'article_affiliate', 8, 'Darf Anzeigen mit Affiliate-URL einstellen (Link auf externen Shop statt Verkauf)');

ALTER TABLE `user`
	CHANGE COLUMN `PAYMENT_ADAPTER_CONFIG` `PAYMENT_ADAPTER_CONFIG` MEDIUMTEXT NOT NULL DEFAULT '' AFTER `AUTOCONFIRM_VENDORS`,
	CHANGE COLUMN `PAYMENT_ADAPTER_SELLER_CONFIG` `PAYMENT_ADAPTER_SELLER_CONFIG` MEDIUMTEXT NOT NULL DEFAULT '' AFTER `PAYMENT_ADAPTER_CONFIG`;
	
UPDATE `infoseite` i 
JOIN `string_info` si ON si.S_TABLE='infoseite' AND si.FK=i.ID_INFOSEITE AND si.BF_LANG=128
SET i.B_SYS=1
WHERE si.V1 IN ('header meta', 'header scripts', 'CODE FUER WEBSTATISTIK')